version: '3.8'

services:
  frontend:
    build: .
    container_name: careflow-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api/v1
    # depends_on:
    #   - app
    networks:
      - careflow-network

networks:
  careflow-network:
    driver: bridge
